### PR TITLE
Reload CSS without doing a hard-refresh of the browser

### PR DESCRIPTION
**Pull request by davej**
As discussed in issue #4

### CODE REVIEW

**Comment by ahmednuaman** [comment]
Sorry @davej, this still seems to refresh the browser, see this video: https://www.youtube.com/watch?v=nqNWZSZeGLg&feature=youtu.be

**Comment by ahmednuaman** [comment]
Also, don't forget to rebase!

**Comment by davej** [comment]
Hmmm, works perfectly for me — the stylesheet updates but the page doesn't refresh (as expected).

From your video it seems that live reload is still triggering on sass files, I'm not sure why that is the case for you but not for me when we should both be running the same code. Here is the output from my console if it helps:

```
>> File "assets/css/partial/_app.sass" changed.

Running "compass:dev" (compass) task
unchanged assets/img/icon-sfab5e12be4.png
overwrite assets/css/styles.css (0.603s)
Compilation took 0.957s

Done, without errors.
Completed in 5.568s at Sun Dec 29 2013 20:28:15 GMT+0000 (GMT) - Waiting...
OK
>> File "assets/css/styles.css" changed.

... Reload assets/css/styles.css ...
Completed in 0.000s at Sun Dec 29 2013 20:28:15 GMT+0000 (GMT) - Waiting...
```

**Comment by ahmednuaman** [comment]
OK, I'll fetch again and check. I created a new repo from your pull request. Are you using the browser plugins or something different?

**Comment by ahmednuaman** [comment]
Bah sorry, I hadn't checked out the correct branch! Yes, looks good. I think it's worth removing `livereload: false` from the `compass` task as it'll default to `false` anyway.

**Comment by davej** [comment]
Cool. Yeah, remove `livereload: false` if you like.

**Pull request merged**
